services:
  web:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./:/application
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=simple-cart.patricksantino.com
      - LETSENCRYPT_HOST=simple-cart.patricksantino.com
    links:
      - php

  php:
      build: ./docker/php-fpm
      restart: unless-stopped
      working_dir: /application
      volumes:
          - ./:/application
          - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini

networks:
  default:
    name: web
    external: true
